### ISSUE TITLE
Update after ocs2 migration

### ISSUE THREAD

**Issue by JuliusSustarevas** [leggedrobotics/perceptive_mpc#1]
Hi
I was wondering if you could help getting this built. I believe the ocs2 repo has migrated from bitbucket to github and lost the version tag.   This causes various issues as some packages e.g. ocs2_comm_interfaces changed name to ocs2_ros_interfaces/ . So I'm  struggling to locate the right versions of everything so this package builds again. 

Thanks for the help,
Julius

**Comment by JuliusSustarevas** [comment]
if anyone has this issues, the OCS2 commit that worked for me was cea7876b4ffea48bb46ddb3a5315ae6e086c5e45

**Comment by JohannesPankert** [comment]
I updated the ros_install files. They should now contain the URL of the new ocs2 repo.
