### ISSUE TITLE
Thread priority

### ISSUE THREAD

**Issue by JuliusSustarevas** [leggedrobotics/perceptive_mpc#4]
Hi
I'm also getting these thread priority warnings:
`WARNING: Failed to set threads priority (one possible reason could be that the user and the group permissions are not set properly.)`

I tried setting user permissions inside /etc/security/limits.conf  But I think I need to do something else?

**Comment by JohannesPankert** [comment]
For me, adding the following settings to `/etc/security/limits.conf` worked:
```
* hard rtprio 99
* soft rtprio 99
```

**Comment by JuliusSustarevas** [comment]
Thanks !
In case someone else finds this: What I was doing wrong is not setting the right flags on my docker container - https://docs.docker.com/config/containers/resource_constraints/

**Comment by tomlankhorst** [comment]
@JuliusSustarevas 
Did you add the  `--ulimit rtprio=99` and `--cap-add=sys_nice` flags?

**Comment by JuliusSustarevas** [comment]
Yes exactly.  that was the issue.  After I added those - the limits.conf worked.

**Comment by licongfei001** [comment]
@JuliusSustarevas 
Could you show the specific operations? I knew little about the docker container therefore I don't know which container to be added those flags
