### ISSUE TITLE
Trajectory time

### ISSUE THREAD

**Issue by JuliusSustarevas** [leggedrobotics/perceptive_mpc#5]
Hi, 
I'm trying to understand how the timing of a trajectory input is being handled.  I'm loading up a 100 point trajectory. The poses are 1cm apart, and timed 1s apart too.  e.g. in pseudocode:

```
costDesiredTrajectories_.desiredTimeTrajectory() =[current_time, current time+1,..., current time+100]
costDesiredTrajectories_.desiredStateTrajectory()=[[0,...], [0.01,...],..., [1,...]] // lets assume the 0 ->1 corresponds to x dimension
```
I am seeing the trajectory being followed, but much much much slower than at 1cm/s cartesian speed. It also slows down as time goes on. 

Am I missing something obvious?  Or am I not using the trajectory command as intended?

**Comment by JohannesPankert** [comment]
That should work. Maybe the `max_linear_velocity` parameter is too low?

**Comment by JuliusSustarevas** [comment]
I'm bypassing that retiming using max_linear_velocity since I am time stamping  desiredTimeTrajectory myself. 

So the behavior I expected is essentially a sliding control horizon of 4 seconds that minimises the sliding cost function also of 4 seconds that slides along the 100s reference trajectory. Is this a correct expectation?

**Comment by JuliusSustarevas** [comment]
Oh, found the issue - my bug. I was doing something silly with timings myself. Thanks for your responses tho. 
It seems to me the above expectation is correct?

**Comment by JohannesPankert** [comment]
That is correct.
