### ISSUE TITLE
ROS Noetic support?

### ISSUE THREAD

**Issue by akmandor** [leggedrobotics/perceptive_mpc#6]
Could you create a new branch or update the code, installation instructions, etc. to make the package work in ROS Noetic?

**Comment by JohannesPankert** [comment]
I currently do not plan to update the code in this repo but I don't expect major changes when using it with Ros noetic. You could try it yourself by changing the base image in the docker file to ros noetic base.

**Comment by Guillaume-Syc** [comment]
Hi !
I've try to install it on noetic, here is the modifications that I did:
- Change voxblox branch to feature/noetic/new_abort_criterion_for_fast_integrator
- git clone catkin_boost_python_buildtool
- git clone numpy_eigen
For now, I have a problem with the raisim package. The cMakeLists file of ocs2_raisim download and execute the main git of https://github.com/leggedrobotics/raisimLib.git but there is no more ros package inside so the package raisim can not be install and I get this error : "Could not find a package configuration file provided by "raisim" with any of the following names"
Is there a git where I can get the right raisim's package ?
And are those modification are good or will it break every thing ?

**Comment by Guillaume-Syc** [comment]
Hi ! 
Apparently, to migrate to noetic you should change voxblox to the noetic branch ( feature/noetic/new_abort_criterion_for_fast_integrator ) 
A second issue is that the gcc compiler changed and I get this error : 
error: use of deleted function ‘ocs2::LinearController<STATE_DIM, INPUT_DIM>::LinearController(ocs2::LinearController<STATE_DIM, INPUT_DIM>&&) [with long unsigned int STATE_DIM = 13; long unsigned int INPUT_DIM = 8]’
Does anyone know how to correct it without changing the compiler version ?
