### ISSUE TITLE
Missing autoconf in docker file

### ISSUE THREAD

**Issue by JuliusSustarevas** [leggedrobotics/perceptive_mpc#8]
Hi

Using the docker build fails.  Complaining about glog not finding autoreconf

I added   autoconf and libtool to system dependencies install (line 11 docker file)

It builds after that but with warnings I've not seen before - hope their ok :)

**Comment by JohannesPankert** [comment]
I have recreated the docker image and could not reproduce the bug. The build works fine for me. I have pushed the image to dockerhub and added the link to the readme for more convenience.

**Comment by JuliusSustarevas** [comment]
If anyone encounters this -> 
Its likely todo with docker setup. In my case it was related to mounting /usr/share.
