### ISSUE TITLE
bad_alloc thrown by getPath

### ISSUE THREAD

**Issue by JuliusSustarevas** [leggedrobotics/perceptive_mpc#9]
Hi, 
This is not really a repo issue I think, but I thought perhaps you've seen anything like this especially in your docker setup.

For some reason I started getting std::bad_alloc error from the line:
'std::string packagePath = ros::package::getPath("perceptive_mpc");' in PerceptiveMpcInterface.cpp

I cannot reproduce it by recloning the repo from scratch. But the error still occurs when I roll back my repo to a state where I've not made any changes from the original fork. So I suspect maybe its a docker issue.  I posted here too https://answers.ros.org/question/393569/rospackagegetpath-throws-bad_alloc/

I understand its probably not a repo problem so feel free to close. But if you have any advice - it will be much appreciated.

**Comment by JohannesPankert** [comment]
Maybe you run out of memory during the build. You can try to pass the `-j 1` flag to `catkin build` to build with a single thread.
I will close this issue since it does not appear to be related to the repo itself.
